# Generated by Django 3.1.3 on 2020-11-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="rationale",
            field=models.TextField(blank=True, default=""),
        ),
    ]
