# Generated by Django 3.1.3 on 2021-02-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(default="", max_length=256),
        ),
    ]
