# Generated by Django 3.1.3 on 2020-12-05 06:35

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameNodeSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shape_id", models.CharField(default="#square", max_length=64)),
                (
                    "fill",
                    colorfield.fields.ColorField(default="#ad560e", max_length=18),
                ),
                (
                    "stroke",
                    colorfield.fields.ColorField(default="#333333", max_length=18),
                ),
                ("stroke_width", models.PositiveSmallIntegerField(default=2)),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("position", "position"),
                            ("submission", "submission"),
                            ("entry", "entry"),
                            ("transition", "transition"),
                            ("sweep", "sweep"),
                            ("takedown", "takedown"),
                            ("guardPull", "guardPull"),
                            ("guardPass", "guardPass"),
                        ],
                        default="position",
                        max_length=50,
                    ),
                ),
                (
                    "game_subtype",
                    models.CharField(
                        choices=[("user", "user"), ("opponent", "opponent")],
                        default="user",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Node Settings",
                "verbose_name_plural": "Game Node Settings",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="BJJ digraph", max_length=256)),
                ("site_url", models.URLField(default="", max_length=256)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="NodeSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.gamenodesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Settings",
                "verbose_name_plural": "Node Settings",
            },
        ),
    ]
