# Generated by Django 3.1.3 on 2020-12-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="name",
            field=models.CharField(default="BJJ digraph", max_length=256),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_url",
            field=models.URLField(default="", max_length=256),
        ),
    ]
