# Generated by Django 3.1.3 on 2020-12-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_auto_20201210_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamenodesettings",
            name="type_text",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="metanodesettings",
            name="type_text",
            field=models.CharField(default="", max_length=64),
        ),
    ]
