# Generated by Django 3.1.3 on 2020-12-05 04:47

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_auto_20201205_0422"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionNodeSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shape_id", models.CharField(max_length=64)),
                (
                    "fill",
                    colorfield.fields.ColorField(default="#ad560e", max_length=18),
                ),
                (
                    "stroke",
                    colorfield.fields.ColorField(default="#333333", max_length=18),
                ),
                ("stroke_width", models.PositiveSmallIntegerField(default=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
