# Generated by Django 3.1.3 on 2020-12-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_auto_20201207_1351"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodesettings",
            name="position",
        ),
        migrations.RemoveField(
            model_name="nodesettings",
            name="transition",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="node_settings",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="site_settings",
        ),
        migrations.AddField(
            model_name="nodesettings",
            name="settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.settings",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.settings",
            ),
        ),
    ]
