# Generated by Django 3.1.3 on 2020-12-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_auto_20201207_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamenodesettings",
            name="node_settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.nodesettings",
            ),
        ),
    ]
