# Generated by Django 3.1.3 on 2020-12-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0005_gamenodesettings_node_settings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NodeSettings",
            new_name="NodesSettings",
        ),
        migrations.AlterModelOptions(
            name="nodessettings",
            options={
                "verbose_name": "Nodes Settings",
                "verbose_name_plural": "Nodes Settings",
            },
        ),
        migrations.RenameField(
            model_name="gamenodesettings",
            old_name="node_settings",
            new_name="nodes_settings",
        ),
    ]
