# Generated by Django 3.1.3 on 2020-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0006_auto_20201207_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamenodesettings",
            name="opacity",
            field=models.PositiveIntegerField(default=90),
        ),
    ]
