# Generated by Django 3.1.3 on 2020-12-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0007_auto_20201214_2205"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nodesettings",
            unique_together={("node_type", "node_subtype")},
        ),
    ]
