# Generated by Django 3.1.3 on 2021-01-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20201214_2207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nodesettings',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='nodesettings',
            name='node_subtype',
        ),
    ]
