# Generated by Django 3.1.3 on 2020-12-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20201207_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamenodesettings',
            name='nodes_settings',
        ),
        migrations.RemoveField(
            model_name='metanodesettings',
            name='nodes_settings',
        ),
        migrations.AddField(
            model_name='gamenodesettings',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.settings'),
        ),
        migrations.AddField(
            model_name='metanodesettings',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.settings'),
        ),
        migrations.DeleteModel(
            name='NodesSettings',
        ),
    ]
