# Generated by Django 3.1.3 on 2020-12-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_auto_20201208_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metanodesettings',
            name='meta_type',
            field=models.CharField(choices=[('comment', 'comment'), ('text', 'text')], default='text', max_length=50),
        ),
    ]
