# Generated by Django 3.1.3 on 2020-12-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergamenodesettings',
            options={'verbose_name': 'User Game Node Settings', 'verbose_name_plural': 'User Game Nodes Settings'},
        ),
    ]
