# Generated by Django 3.1.3 on 2020-12-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_auto_20201208_1311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergamenodesettings',
            unique_together=set(),
        ),
    ]
