# Generated by Django 3.1.3 on 2020-12-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_settings", "0003_auto_20201208_1442"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usermetanodesettings",
            unique_together=set(),
        ),
    ]
