# Generated by Django 3.1.3 on 2021-01-08 10:14

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_settings', '0011_auto_20210107_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergamenodesettings',
            name='node_type',
        ),
        migrations.RemoveField(
            model_name='usermetanodesettings',
            name='node_type',
        ),
        migrations.AlterField(
            model_name='usergamenodesettings',
            name='game_subtype',
            field=models.CharField(choices=[('user', 'user'), ('opponent', 'opponent')], default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='usergamenodesettings',
            name='game_type',
            field=models.CharField(choices=[('position', 'position'), ('submission', 'submission'), ('entry', 'entry'), ('transition', 'transition'), ('sweep', 'sweep'), ('takedown', 'takedown'), ('guardPull', 'guardPull'), ('guardPass', 'guardPass')], default='position', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermetanodesettings',
            name='meta_type',
            field=models.CharField(choices=[('comment', 'comment'), ('text', 'text')], default='comment', max_length=50),
        ),
        migrations.CreateModel(
            name='UserNodeSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shape_id', models.CharField(default='#square', max_length=64)),
                ('type_text', models.CharField(default='', max_length=64)),
                ('fill', colorfield.fields.ColorField(default='#ad560e', max_length=18)),
                ('fill_opacity', models.FloatField(default=1.0)),
                ('stroke', colorfield.fields.ColorField(default='#333333', max_length=18)),
                ('stroke_opacity', models.FloatField(default=1.0)),
                ('stroke_width', models.PositiveSmallIntegerField(default=2)),
                ('node_type', models.CharField(choices=[('score-entry-user', 'score-entry-user'), ('score-entry-opponent', 'score-entry-opponent'), ('score-position-user', 'score-position-user'), ('score-position-opponent', 'score-position-opponent'), ('score-guardpass-user', 'score-guardpass-user'), ('score-guardpass-opponent', 'score-guardpass-opponent'), ('score-guardpull-user', 'score-guardpull-user'), ('score-guardpull-opponent', 'score-guardpull-opponent'), ('score-submission-user', 'score-submission-user'), ('score-submission-opponent', 'score-submission-opponent'), ('score-takedown-user', 'score-takedown-user'), ('score-takedown-opponent', 'score-takedown-opponent'), ('score-sweep-user', 'score-sweep-user'), ('score-sweep-opponent', 'score-sweep-opponent'), ('score-transition-user', 'score-transition-user'), ('score-transition-opponent', 'score-transition-opponent'), ('meta-comment', 'meta-comment'), ('meta-text', 'meta-text')], default='', max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Node Settings',
                'verbose_name_plural': 'User Nodes Settings',
                'unique_together': {('owner', 'node_type')},
            },
        ),
    ]
