# Generated by Django 3.1.3 on 2021-01-28 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0014_auto_20210128_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernodesettings',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)]),
        ),
    ]
