# Generated by Django 3.1.3 on 2020-12-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettings",
            old_name="name",
            new_name="title",
        ),
    ]
