# Generated by Django 3.1.3 on 2020-12-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_auto_20201211_1347"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamenodesettings",
            name="fill_opacity",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="metanodesettings",
            name="fill_opacity",
            field=models.FloatField(default=1.0),
        ),
    ]
