# Generated by Django 3.1.3 on 2021-01-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0011_auto_20210107_1345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamenodesettings",
            name="game_subtype",
            field=models.CharField(
                choices=[("user", "user"), ("opponent", "opponent")],
                default="user",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="gamenodesettings",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("position", "position"),
                    ("submission", "submission"),
                    ("entry", "entry"),
                    ("transition", "transition"),
                    ("sweep", "sweep"),
                    ("takedown", "takedown"),
                    ("guardPull", "guardPull"),
                    ("guardPass", "guardPass"),
                ],
                default="position",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="metanodesettings",
            name="meta_type",
            field=models.CharField(
                choices=[("comment", "comment"), ("text", "text")],
                default="text",
                max_length=50,
            ),
        ),
    ]
