# Generated by Django 3.1.3 on 2021-01-17 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_auto_20210108_1310"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scorenode",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="scorenode",
            name="effectiveness",
        ),
        migrations.RemoveField(
            model_name="scorenode",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="scorenode",
            name="proficiency",
        ),
        migrations.AddField(
            model_name="scorenode",
            name="rationale",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="scorenode",
            name="score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
