# Generated by Django 3.1.3 on 2020-11-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0003_graph_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="slug",
            field=models.SlugField(default="", max_length=200),
        ),
    ]
