# Generated by Django 3.1.3 on 2020-12-01 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("graphs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="", max_length=200, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "graph",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="graphs.graph"
                    ),
                ),
            ],
        ),
    ]
