# Generated by Django 3.1.3 on 2020-12-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shapes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodeshape",
            name="opacity",
            field=models.CharField(default="100", max_length=3),
        ),
    ]
