# Generated by Django 3.1.3 on 2020-12-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shapes", "0003_auto_20201204_2320"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodeshape",
            name="fill",
            field=models.CharField(default="#DDDDDD", max_length=20),
        ),
        migrations.AlterField(
            model_name="nodeshape",
            name="stroke",
            field=models.CharField(default="#333333", max_length=20),
        ),
    ]
