# Generated by Django 3.1.3 on 2021-02-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
