# Generated by Django 3.1.3 on 2020-12-08 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_settings", "0004_auto_20201208_1550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergamenodesettings",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_settings_usergamenodesettings_related",
                related_query_name="user_settings_usergamenodesettingss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usermetanodesettings",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_settings_usermetanodesettings_related",
                related_query_name="user_settings_usermetanodesettingss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
