# Generated by Django 3.1.3 on 2020-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_settings", "0007_auto_20201214_1822"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergamenodesettings",
            name="opacity",
        ),
        migrations.RemoveField(
            model_name="usermetanodesettings",
            name="opacity",
        ),
        migrations.AddField(
            model_name="usergamenodesettings",
            name="stroke_opacity",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="usermetanodesettings",
            name="stroke_opacity",
            field=models.FloatField(default=1.0),
        ),
    ]
