# Generated by Django 3.1.3 on 2021-01-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_settings", "0012_auto_20210108_1014"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermetanodesettings",
            name="owner",
        ),
        migrations.DeleteModel(
            name="UserGameNodeSettings",
        ),
        migrations.DeleteModel(
            name="UserMetaNodeSettings",
        ),
    ]
