# Generated by Django 3.1.3 on 2020-11-10 22:37

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("position", "position"),
                            ("submission", "submission"),
                            ("entry", "entry"),
                            ("transition", "transition"),
                            ("sweep", "sweep"),
                            ("conditional", "conditional"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("comment", models.TextField(blank=True, default="")),
                ("effectiveness", models.IntegerField(default=50)),
                ("priority", models.IntegerField(default=50)),
                ("proficiency", models.IntegerField(default=50)),
                ("position_x", models.FloatField(default=100)),
                ("position_y", models.FloatField(default=100)),
            ],
            options={
                "verbose_name": "Node",
                "verbose_name_plural": "Nodes",
            },
        ),
    ]
