# Generated by Django 3.1.3 on 2020-12-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamenode",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("position", "position"),
                    ("submission", "submission"),
                    ("entry", "entry"),
                    ("transition", "transition"),
                    ("sweep", "sweep"),
                    ("takedown", "takedown"),
                    ("guardPull", "guardPull"),
                    ("guardPass", "guardPass"),
                ],
                default="position",
                max_length=50,
            ),
        ),
    ]
