# Generated by Django 3.1.3 on 2020-12-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_auto_20201202_1717"),
    ]

    operations = [
        migrations.AddField(
            model_name="metanode",
            name="meta_type",
            field=models.CharField(
                choices=[("comment", "comment"), ("text", "text")],
                default="comment",
                max_length=50,
            ),
        ),
    ]
