# Generated by Django 3.1.3 on 2020-11-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20201105_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
