# Generated by Django 3.1.3 on 2020-12-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0003_metanode_meta_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamenode",
            name="game_subtype",
            field=models.CharField(choices=[], default="user", max_length=50),
        ),
        migrations.AlterField(
            model_name="gamenode",
            name="game_type",
            field=models.CharField(choices=[], default="position", max_length=50),
        ),
    ]
